### PR TITLE
Add David Banitongwa

### PR DESCRIPTION
**Pull request by Banitongwa7**

### CODE REVIEW

**Review by amyyalex — CHANGES_REQUESTED** [review]
There seems to be a conflict with these changes. Your information has replaced the 'cardDetailsArray' data instead of adding a new object into the array right under the 'cardDetailsArray', as needed. Could you please add the new object separately rather than nesting it inside? Thank you for your attention to this! x

**Comment by Banitongwa7** [comment]
Thank you for your comment. I added a new object.

**Comment by amyyalex** [comment]
Yes it does! x

**Comment by Banitongwa7** [comment]
Glad to hear it !

**Pull request merged**
