### PR TITLE
added my detail

### PR DESCRIPTION
**Pull request by Ademola111**
Added my details

### CODE REVIEW

**Review by Ademola111 — COMMENTED** [review]
Based on the translation, I am on a lookout for a free language translation API to use for the translation implementation at the backend. I hope the little implementation added will go a long way. I hope to hear back from you if you lay your hands on a free api that i can use to complete this feature and functionality. warm regards.

**Comment by amyyalex** [comment]
Hi Ademola, thank you for your valuable contribution! I'll certainly find a free tool for language translation and keep you updated. Meanwhile, I would like you to enhance the language translator's design for better visual appeal and centre alignment (see the attached image for reference). Thanks again for your input - eagerly anticipating the improvements you'll bring. Warm regards.
language_selection

**Comment by Ademola111** [comment]
Hi Amyy,

Thank you for reaching out I really appreciate it.

Going forward I would like to know if my PR have been merged so that I can
fetch the main branch to effect the image because I deleted the branch from
my end after committing.

Warm regards.

**Comment by amyyalex** [comment]
Hi Ademola,  
I have just merged your PR, so you can go ahead and fetch! x

**Comment by Ademola111** [comment]
Hi Amyyalex,

Thank you for your prompt response. I am glad to contribute. Going forward
I’ll be on a look out for free api to use. Haven’t get any but will keep my
hope high and I’ll be expecting from you too.

In addition, the image attached in the previous mail can it be added in
piece to the image folder for ease access.

Thank you.

**Comment by amyyalex** [comment]
Hi @Ademola111,
The image is just an example to reference to and have an idea. Hence why it not linked or added to the image.

**Pull request merged**
