### PR TITLE
Banner Update

### PR DESCRIPTION
**Pull request by zealshah29**
I have formatted the header text and para of the banner to make it easy to read/

### CODE REVIEW

**Comment by amyyalex** [comment]
Hi @zealshah29 
Can I see a screenshot of the changes you made?
Thanks

**Comment by zealshah29** [comment]
Hi so I accidentally forked this repo: https://github.com/AbdessamadTzn/simple-contribution
And made changes over there, and then created a pull request on that forked repository.

**Comment by zealshah29** [comment]
image
Here's the changes I made

**Comment by amyyalex** [comment]
Hi @zealshah29 
It looks like you forked the old banner 
This is what the banner looks like now
SC banner

**Comment by zealshah29** [comment]
Yes, but I am unable to fork your repository since I already forked the other one. Is it possible for me to make changes on the updated code and create a pull request on your repository?

**Pull request closed without merging**
