### PR TITLE
add animation

### PR DESCRIPTION
**Pull request by Banitongwa7**

### CODE REVIEW

**Review by amyyalex — CHANGES_REQUESTED** [review]
Hi @Banitongwa7,

Thank you for your recent changes! I appreciate the animation you added; it brings the site to life. However, I feel the banner section might be better without animation. Also, I noticed that the contribute section appears to be broken, so could you please take a look at that? Your contributions are valued! Thanks again! 😊

**Comment by Banitongwa7** [comment]
I removed the animation to banner section. 
Can you send me the screenshot of the section that is not displayed correctly ?

On my side, everything works correctly.

**Comment by amyyalex** [comment]
You know what, it seems to work perfectly fine on my end now so it's all good! x

**Comment by Banitongwa7** [comment]
Glad to hear it !

**Pull request merged**
