### PR TITLE
Updated first contribution cardDetails.json

### PR DESCRIPTION
**Pull request by WairimuMaringa**

### CODE REVIEW

**Comment by WairimuMaringa** [comment]
Added details to card.json, practicing how to contribute to open source

**Comment by amyyalex** [comment]
PR MERGED!
Thanks for contributing :)

**Comment by amyyalex** [comment]
'practicing how to contribute to open source'
I hope you found contributing to this project easy 👍🏾

**Comment by WairimuMaringa** [comment]
Yes I did!!
Thank you so much!!


*'That without experimentation, a willingness to ask questions and try new
things, we shall surely become static, repetitive, moribund*.' - Antony
Bourdain

**Pull request merged**
