### PR TITLE
Updated Search Filter

### PR DESCRIPTION
**Pull request by SreekakulamLohith**
Added Sreekakulam Lohith card info and updated search filter.

### CODE REVIEW

**Comment by SreekakulamLohith** [comment]
@amyyalex can you please review my pull request?

**Comment by amyyalex** [comment]
> @amyyalex can you please review my pull request?

On it @SreekakulamLohith 
I also see that you made a change to this function "(details) => details.name.toLowerCase().includes(searchValue)" to "(details) => details.name.toLowerCase().startsWith(searchValue.toLowerCase())" 
Can you explain the change?

**Comment by SreekakulamLohith** [comment]
Screenshot 2023-12-19 165024

**Comment by SreekakulamLohith** [comment]
using include()
Screenshot 2023-12-19 191957

**Comment by SreekakulamLohith** [comment]
@amyyalex  startsWith() will give the exact names present in json file while includes() is less accurate in providing exact names.

**Comment by amyyalex** [comment]
Okay that explains it better!
Thanks for contribution @SreekakulamLohith 
Will go ahead and merge now.

**Pull request merged**
